# Generated by Django 2.2 on 2019-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_auto_20190709_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='Enter Description Here'),
        ),
        migrations.AddField(
            model_name='department',
            name='map_url',
            field=models.URLField(default='http://localhost', verbose_name='Map URL'),
        ),
    ]
