# Generated by Django 2.2 on 2019-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_auto_20190709_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='departments/', verbose_name='Department Cover Photo'),
        ),
    ]
