# Generated by Django 2.2 on 2019-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0004_department_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='chairman',
            field=models.CharField(default='Not Set', max_length=50, verbose_name='Chairman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.CharField(default='Not Set', max_length=50, verbose_name='Dean'),
            preserve_default=False,
        ),
    ]
