# Generated by Django 2.2 on 2019-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_auto_20190709_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='vips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'vips',
                'verbose_name_plural': 'vipss',
            },
        ),
    ]
